CREATE TABLE PROFILES (
    PROFILE_ID SERIAL PRIMARY KEY,
    BIO TEXT,
    BIRTH_DATE DATE NOT NULL, -- Usado para calcular rango de edad
    GENDER VARCHAR(50),
    LOCATION_ADDRESS VARCHAR(255),
    CITY VARCHAR(100),
    SPORTS_INTERESTS TEXT,
    SEARCH_RADIUS INTEGER, -- En kilómetros
    LANGUAGES TEXT
);
